/**
 * generated by Xtext
 */
package uk.ac.kcl.inf.zschaler.gridgames.ui.contentassist;

import uk.ac.kcl.inf.zschaler.gridgames.ui.contentassist.AbstractGridGameProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class GridGameProposalProvider extends AbstractGridGameProposalProvider {
}
