/*
 * generated by Xtext
 */
package uk.ac.kcl.inf.zschaler.gridgames.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class GridGameUiModule extends uk.ac.kcl.inf.zschaler.gridgames.ui.AbstractGridGameUiModule {
	public GridGameUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
