/*
 * generated by Xtext
 */
package uk.ac.kcl.inf.zschaler.gridgames;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class GridGameRuntimeModule extends uk.ac.kcl.inf.zschaler.gridgames.AbstractGridGameRuntimeModule {

}
