/*
 * generated by Xtext
 */
package uk.ac.kcl.inf.zschaler.gridgames;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class GridGameStandaloneSetup extends GridGameStandaloneSetupGenerated{

	public static void doSetup() {
		new GridGameStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

