/**
 * generated by Xtext
 */
package uk.ac.kcl.inf.zschaler.gridgames.scoping;

import com.google.common.base.Objects;
import java.util.List;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EReference;
import org.eclipse.xtext.EcoreUtil2;
import org.eclipse.xtext.scoping.IScope;
import org.eclipse.xtext.scoping.Scopes;
import org.eclipse.xtext.scoping.impl.AbstractDeclarativeScopeProvider;
import uk.ac.kcl.inf.zschaler.gridgames.gridGame.CellSpecification;
import uk.ac.kcl.inf.zschaler.gridgames.gridGame.GridGamePackage;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class GridGameScopeProvider extends AbstractDeclarativeScopeProvider {
  @Override
  public IScope getScope(final EObject context, final EReference reference) {
    EClass _eReferenceType = reference.getEReferenceType();
    boolean _equals = Objects.equal(_eReferenceType, GridGamePackage.Literals.CELL_SPECIFICATION);
    if (_equals) {
      EObject rootElement = EcoreUtil2.getRootContainer(context);
      List<? extends EObject> candidates = EcoreUtil2.<CellSpecification>getAllContentsOfType(rootElement, CellSpecification.class);
      return Scopes.scopeFor(candidates);
    } else {
      return super.getScope(context, reference);
    }
  }
}
