/**
 * generated by Xtext
 */
package uk.ac.kcl.inf.zschaler.gridgames.generator;

import org.eclipse.emf.ecore.resource.Resource;
import org.eclipse.xtext.generator.IFileSystemAccess;
import org.eclipse.xtext.generator.IGenerator;
import uk.ac.kcl.inf.zschaler.gridgames.generator.CellGenerator;
import uk.ac.kcl.inf.zschaler.gridgames.generator.FieldGenerator;
import uk.ac.kcl.inf.zschaler.gridgames.generator.FrameGenerator;
import uk.ac.kcl.inf.zschaler.gridgames.generator.ModelPreprocessor;

/**
 * Generates code from your model files on save.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#code-generation
 */
@SuppressWarnings("all")
public class GridGameGenerator implements IGenerator {
  @Override
  public void doGenerate(final Resource resource, final IFileSystemAccess fsa) {
    final ModelPreprocessor processedModel = new ModelPreprocessor(resource);
    new CellGenerator(processedModel).generate(fsa);
    new FieldGenerator(processedModel).generate(fsa);
    new FrameGenerator(processedModel).generate(fsa);
  }
}
