/*
 * generated by Xtext 2.18.0.M3
 */
package uk.ac.kcl.inf.szschaler.gridgames


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class GridGameRuntimeModule extends AbstractGridGameRuntimeModule {
}
