/*
 * generated by Xtext 2.18.0.M3
 */
package uk.ac.kcl.inf.szschaler.gridgames.ide


/**
 * Use this class to register ide components.
 */
class GridGameIdeModule extends AbstractGridGameIdeModule {
}
