/*
 * generated by Xtext
 */
package uk.ac.kcl.inf.zschaler.gridgames.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import uk.ac.kcl.inf.zschaler.gridgames.services.GridGameGrammarAccess;

public class GridGameParser extends AbstractContentAssistParser {
	
	@Inject
	private GridGameGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected uk.ac.kcl.inf.zschaler.gridgames.ui.contentassist.antlr.internal.InternalGridGameParser createParser() {
		uk.ac.kcl.inf.zschaler.gridgames.ui.contentassist.antlr.internal.InternalGridGameParser result = new uk.ac.kcl.inf.zschaler.gridgames.ui.contentassist.antlr.internal.InternalGridGameParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getGridGameAccess().getAlternatives_3(), "rule__GridGame__Alternatives_3");
					put(grammarAccess.getCellMemberAccess().getAlternatives(), "rule__CellMember__Alternatives");
					put(grammarAccess.getCellDisplaySpecAccess().getDisplay_typeAlternatives_3_0(), "rule__CellDisplaySpec__Display_typeAlternatives_3_0");
					put(grammarAccess.getCellDisplaySpecAccess().getAlternatives_4(), "rule__CellDisplaySpec__Alternatives_4");
					put(grammarAccess.getCellDisplaySpecAccess().getColorAlternatives_4_2_1_0(), "rule__CellDisplaySpec__ColorAlternatives_4_2_1_0");
					put(grammarAccess.getVarSpecAccess().getAlternatives(), "rule__VarSpec__Alternatives");
					put(grammarAccess.getCellVarSpecAccess().getTypeAlternatives_1_0(), "rule__CellVarSpec__TypeAlternatives_1_0");
					put(grammarAccess.getParamSpecAccess().getTypeAlternatives_0_0(), "rule__ParamSpec__TypeAlternatives_0_0");
					put(grammarAccess.getCellStateSpecAccess().getAlternatives(), "rule__CellStateSpec__Alternatives");
					put(grammarAccess.getValueAccess().getAlternatives(), "rule__Value__Alternatives");
					put(grammarAccess.getTransitionTriggerSpecAccess().getAlternatives(), "rule__TransitionTriggerSpec__Alternatives");
					put(grammarAccess.getMouseTriggerAccess().getAlternatives(), "rule__MouseTrigger__Alternatives");
					put(grammarAccess.getCellStateBehaviourAccess().getAlternatives(), "rule__CellStateBehaviour__Alternatives");
					put(grammarAccess.getDirectBehaviourAccess().getAlternatives(), "rule__DirectBehaviour__Alternatives");
					put(grammarAccess.getOptionSpecificationAccess().getAlternatives(), "rule__OptionSpecification__Alternatives");
					put(grammarAccess.getFieldInitialisationsAccess().getAlternatives(), "rule__FieldInitialisations__Alternatives");
					put(grammarAccess.getFieldInitialisationAccess().getAlternatives(), "rule__FieldInitialisation__Alternatives");
					put(grammarAccess.getRandomInitialisationAccess().getAlternatives_4(), "rule__RandomInitialisation__Alternatives_4");
					put(grammarAccess.getAtomicExpressionAccess().getAlternatives(), "rule__AtomicExpression__Alternatives");
					put(grammarAccess.getCountExpressionAccess().getOpAlternatives_4_0_0(), "rule__CountExpression__OpAlternatives_4_0_0");
					put(grammarAccess.getGridGameAccess().getGroup(), "rule__GridGame__Group__0");
					put(grammarAccess.getCellSpecificationAccess().getGroup(), "rule__CellSpecification__Group__0");
					put(grammarAccess.getCellDisplaySpecAccess().getGroup(), "rule__CellDisplaySpec__Group__0");
					put(grammarAccess.getCellDisplaySpecAccess().getGroup_4_0(), "rule__CellDisplaySpec__Group_4_0__0");
					put(grammarAccess.getCellDisplaySpecAccess().getGroup_4_1(), "rule__CellDisplaySpec__Group_4_1__0");
					put(grammarAccess.getCellDisplaySpecAccess().getGroup_4_2(), "rule__CellDisplaySpec__Group_4_2__0");
					put(grammarAccess.getCellVarSpecAccess().getGroup(), "rule__CellVarSpec__Group__0");
					put(grammarAccess.getGlobalCellStateSpecAccess().getGroup(), "rule__GlobalCellStateSpec__Group__0");
					put(grammarAccess.getGlobalCellStateSpecAccess().getGroup_2(), "rule__GlobalCellStateSpec__Group_2__0");
					put(grammarAccess.getGlobalCellStateSpecAccess().getGroup_2_2(), "rule__GlobalCellStateSpec__Group_2_2__0");
					put(grammarAccess.getParamSpecAccess().getGroup(), "rule__ParamSpec__Group__0");
					put(grammarAccess.getLocalCellStateSpecAccess().getGroup(), "rule__LocalCellStateSpec__Group__0");
					put(grammarAccess.getCellStateSpecReferenceAccess().getGroup(), "rule__CellStateSpecReference__Group__0");
					put(grammarAccess.getCellStateSpecReferenceAccess().getGroup_2(), "rule__CellStateSpecReference__Group_2__0");
					put(grammarAccess.getCellStateSpecReferenceAccess().getGroup_2_2(), "rule__CellStateSpecReference__Group_2_2__0");
					put(grammarAccess.getCellStateAccess().getGroup(), "rule__CellState__Group__0");
					put(grammarAccess.getCellStateAccess().getGroup_3(), "rule__CellState__Group_3__0");
					put(grammarAccess.getCellStateAccess().getGroup_4(), "rule__CellState__Group_4__0");
					put(grammarAccess.getCellStateAccess().getGroup_4_3(), "rule__CellState__Group_4_3__0");
					put(grammarAccess.getTransitionSpecAccess().getGroup(), "rule__TransitionSpec__Group__0");
					put(grammarAccess.getMouseTriggerAccess().getGroup_1(), "rule__MouseTrigger__Group_1__0");
					put(grammarAccess.getContextTriggerAccess().getGroup(), "rule__ContextTrigger__Group__0");
					put(grammarAccess.getDirectBehaviourAccess().getGroup_1(), "rule__DirectBehaviour__Group_1__0");
					put(grammarAccess.getEndGameBehaviourAccess().getGroup(), "rule__EndGameBehaviour__Group__0");
					put(grammarAccess.getFieldSpecificationAccess().getGroup(), "rule__FieldSpecification__Group__0");
					put(grammarAccess.getAllowRestartMenuAccess().getGroup(), "rule__AllowRestartMenu__Group__0");
					put(grammarAccess.getStartFieldDeclarationAccess().getGroup(), "rule__StartFieldDeclaration__Group__0");
					put(grammarAccess.getGenerationalContextsAccess().getGroup(), "rule__GenerationalContexts__Group__0");
					put(grammarAccess.getGlobalFieldInitialisationAccess().getGroup(), "rule__GlobalFieldInitialisation__Group__0");
					put(grammarAccess.getGlobalFieldInitialisationAccess().getGroup_2(), "rule__GlobalFieldInitialisation__Group_2__0");
					put(grammarAccess.getGlobalFieldInitialisationAccess().getGroup_2_2(), "rule__GlobalFieldInitialisation__Group_2_2__0");
					put(grammarAccess.getGlobalFieldInitialisationAccess().getGroup_4(), "rule__GlobalFieldInitialisation__Group_4__0");
					put(grammarAccess.getFieldInitialisationsRefAccess().getGroup(), "rule__FieldInitialisationsRef__Group__0");
					put(grammarAccess.getFieldInitialisationsRefAccess().getGroup_2(), "rule__FieldInitialisationsRef__Group_2__0");
					put(grammarAccess.getFieldInitialisationsRefAccess().getGroup_2_2(), "rule__FieldInitialisationsRef__Group_2_2__0");
					put(grammarAccess.getLocalFieldInitialisationsAccess().getGroup(), "rule__LocalFieldInitialisations__Group__0");
					put(grammarAccess.getLocalFieldInitialisationsAccess().getGroup_2(), "rule__LocalFieldInitialisations__Group_2__0");
					put(grammarAccess.getDefaultInitialisationAccess().getGroup(), "rule__DefaultInitialisation__Group__0");
					put(grammarAccess.getRandomInitialisationAccess().getGroup(), "rule__RandomInitialisation__Group__0");
					put(grammarAccess.getContextInitialisationAccess().getGroup(), "rule__ContextInitialisation__Group__0");
					put(grammarAccess.getContextExpressionAccess().getGroup(), "rule__ContextExpression__Group__0");
					put(grammarAccess.getContextExpressionAccess().getGroup_1(), "rule__ContextExpression__Group_1__0");
					put(grammarAccess.getFilterExpressionAccess().getGroup(), "rule__FilterExpression__Group__0");
					put(grammarAccess.getStateFilterExpressionAccess().getGroup(), "rule__StateFilterExpression__Group__0");
					put(grammarAccess.getCountExpressionAccess().getGroup(), "rule__CountExpression__Group__0");
					put(grammarAccess.getCountExpressionAccess().getGroup_4(), "rule__CountExpression__Group_4__0");
					put(grammarAccess.getNotEmptyExpressionAccess().getGroup(), "rule__NotEmptyExpression__Group__0");
					put(grammarAccess.getGridGameAccess().getNameAssignment_1(), "rule__GridGame__NameAssignment_1");
					put(grammarAccess.getGridGameAccess().getStatesAssignment_3_0(), "rule__GridGame__StatesAssignment_3_0");
					put(grammarAccess.getGridGameAccess().getCellsAssignment_3_1(), "rule__GridGame__CellsAssignment_3_1");
					put(grammarAccess.getGridGameAccess().getInitsAssignment_3_2(), "rule__GridGame__InitsAssignment_3_2");
					put(grammarAccess.getGridGameAccess().getFieldsAssignment_3_3(), "rule__GridGame__FieldsAssignment_3_3");
					put(grammarAccess.getGridGameAccess().getOptionsAssignment_3_4(), "rule__GridGame__OptionsAssignment_3_4");
					put(grammarAccess.getCellSpecificationAccess().getNameAssignment_1(), "rule__CellSpecification__NameAssignment_1");
					put(grammarAccess.getCellSpecificationAccess().getMembersAssignment_3(), "rule__CellSpecification__MembersAssignment_3");
					put(grammarAccess.getCellDisplaySpecAccess().getDisplay_typeAssignment_3(), "rule__CellDisplaySpec__Display_typeAssignment_3");
					put(grammarAccess.getCellDisplaySpecAccess().getTextAssignment_4_0_1(), "rule__CellDisplaySpec__TextAssignment_4_0_1");
					put(grammarAccess.getCellDisplaySpecAccess().getVarAssignment_4_1_1(), "rule__CellDisplaySpec__VarAssignment_4_1_1");
					put(grammarAccess.getCellDisplaySpecAccess().getColorAssignment_4_2_1(), "rule__CellDisplaySpec__ColorAssignment_4_2_1");
					put(grammarAccess.getCellVarSpecAccess().getTypeAssignment_1(), "rule__CellVarSpec__TypeAssignment_1");
					put(grammarAccess.getCellVarSpecAccess().getNameAssignment_2(), "rule__CellVarSpec__NameAssignment_2");
					put(grammarAccess.getGlobalCellStateSpecAccess().getNameAssignment_1(), "rule__GlobalCellStateSpec__NameAssignment_1");
					put(grammarAccess.getGlobalCellStateSpecAccess().getParamsAssignment_2_1(), "rule__GlobalCellStateSpec__ParamsAssignment_2_1");
					put(grammarAccess.getGlobalCellStateSpecAccess().getParamsAssignment_2_2_1(), "rule__GlobalCellStateSpec__ParamsAssignment_2_2_1");
					put(grammarAccess.getGlobalCellStateSpecAccess().getStatesAssignment_4(), "rule__GlobalCellStateSpec__StatesAssignment_4");
					put(grammarAccess.getGlobalCellStateSpecAccess().getStartAssignment_7(), "rule__GlobalCellStateSpec__StartAssignment_7");
					put(grammarAccess.getParamSpecAccess().getTypeAssignment_0(), "rule__ParamSpec__TypeAssignment_0");
					put(grammarAccess.getParamSpecAccess().getNameAssignment_1(), "rule__ParamSpec__NameAssignment_1");
					put(grammarAccess.getLocalCellStateSpecAccess().getStatesAssignment_2(), "rule__LocalCellStateSpec__StatesAssignment_2");
					put(grammarAccess.getLocalCellStateSpecAccess().getStartAssignment_5(), "rule__LocalCellStateSpec__StartAssignment_5");
					put(grammarAccess.getCellStateSpecReferenceAccess().getStateSpecAssignment_1(), "rule__CellStateSpecReference__StateSpecAssignment_1");
					put(grammarAccess.getCellStateSpecReferenceAccess().getParamsAssignment_2_1(), "rule__CellStateSpecReference__ParamsAssignment_2_1");
					put(grammarAccess.getCellStateSpecReferenceAccess().getParamsAssignment_2_2_1(), "rule__CellStateSpecReference__ParamsAssignment_2_2_1");
					put(grammarAccess.getStringValueAccess().getValueAssignment(), "rule__StringValue__ValueAssignment");
					put(grammarAccess.getIntValueAccess().getValueAssignment(), "rule__IntValue__ValueAssignment");
					put(grammarAccess.getVarRefValueAccess().getRefAssignment(), "rule__VarRefValue__RefAssignment");
					put(grammarAccess.getCellStateAccess().getNameAssignment_0(), "rule__CellState__NameAssignment_0");
					put(grammarAccess.getCellStateAccess().getDisplayAssignment_2(), "rule__CellState__DisplayAssignment_2");
					put(grammarAccess.getCellStateAccess().getTransitionsAssignment_3_2(), "rule__CellState__TransitionsAssignment_3_2");
					put(grammarAccess.getCellStateAccess().getOnEnterAssignment_4_2(), "rule__CellState__OnEnterAssignment_4_2");
					put(grammarAccess.getCellStateAccess().getOnEnterAssignment_4_3_1(), "rule__CellState__OnEnterAssignment_4_3_1");
					put(grammarAccess.getTransitionSpecAccess().getTriggerAssignment_1(), "rule__TransitionSpec__TriggerAssignment_1");
					put(grammarAccess.getTransitionSpecAccess().getTargetAssignment_3(), "rule__TransitionSpec__TargetAssignment_3");
					put(grammarAccess.getMouseTriggerAccess().getLeftAssignment_0(), "rule__MouseTrigger__LeftAssignment_0");
					put(grammarAccess.getContextTriggerAccess().getExpAssignment_2(), "rule__ContextTrigger__ExpAssignment_2");
					put(grammarAccess.getBehaviourReferenceAccess().getRefAssignment(), "rule__BehaviourReference__RefAssignment");
					put(grammarAccess.getEndGameBehaviourAccess().getMessageAssignment_2(), "rule__EndGameBehaviour__MessageAssignment_2");
					put(grammarAccess.getFieldSpecificationAccess().getNameAssignment_1(), "rule__FieldSpecification__NameAssignment_1");
					put(grammarAccess.getFieldSpecificationAccess().getWidthAssignment_5(), "rule__FieldSpecification__WidthAssignment_5");
					put(grammarAccess.getFieldSpecificationAccess().getHeightAssignment_8(), "rule__FieldSpecification__HeightAssignment_8");
					put(grammarAccess.getFieldSpecificationAccess().getField_initialisationAssignment_9(), "rule__FieldSpecification__Field_initialisationAssignment_9");
					put(grammarAccess.getStartFieldDeclarationAccess().getFieldAssignment_2(), "rule__StartFieldDeclaration__FieldAssignment_2");
					put(grammarAccess.getGlobalFieldInitialisationAccess().getNameAssignment_1(), "rule__GlobalFieldInitialisation__NameAssignment_1");
					put(grammarAccess.getGlobalFieldInitialisationAccess().getParamsAssignment_2_1(), "rule__GlobalFieldInitialisation__ParamsAssignment_2_1");
					put(grammarAccess.getGlobalFieldInitialisationAccess().getParamsAssignment_2_2_1(), "rule__GlobalFieldInitialisation__ParamsAssignment_2_2_1");
					put(grammarAccess.getGlobalFieldInitialisationAccess().getInitialisationsAssignment_4_0(), "rule__GlobalFieldInitialisation__InitialisationsAssignment_4_0");
					put(grammarAccess.getFieldInitialisationsRefAccess().getRefAssignment_1(), "rule__FieldInitialisationsRef__RefAssignment_1");
					put(grammarAccess.getFieldInitialisationsRefAccess().getParamsAssignment_2_1(), "rule__FieldInitialisationsRef__ParamsAssignment_2_1");
					put(grammarAccess.getFieldInitialisationsRefAccess().getParamsAssignment_2_2_1(), "rule__FieldInitialisationsRef__ParamsAssignment_2_2_1");
					put(grammarAccess.getLocalFieldInitialisationsAccess().getInitialisationsAssignment_2_0(), "rule__LocalFieldInitialisations__InitialisationsAssignment_2_0");
					put(grammarAccess.getDefaultInitialisationAccess().getCellAssignment_2(), "rule__DefaultInitialisation__CellAssignment_2");
					put(grammarAccess.getRandomInitialisationAccess().getCellAssignment_2(), "rule__RandomInitialisation__CellAssignment_2");
					put(grammarAccess.getRandomInitialisationAccess().getCountAssignment_4_0(), "rule__RandomInitialisation__CountAssignment_4_0");
					put(grammarAccess.getRandomInitialisationAccess().getVarAssignment_4_1(), "rule__RandomInitialisation__VarAssignment_4_1");
					put(grammarAccess.getContextInitialisationAccess().getCellAssignment_2(), "rule__ContextInitialisation__CellAssignment_2");
					put(grammarAccess.getContextInitialisationAccess().getCheckAssignment_4(), "rule__ContextInitialisation__CheckAssignment_4");
					put(grammarAccess.getContextInitialisationAccess().getExpAssignment_7(), "rule__ContextInitialisation__ExpAssignment_7");
					put(grammarAccess.getContextExpressionAccess().getSub_expAssignment_0(), "rule__ContextExpression__Sub_expAssignment_0");
					put(grammarAccess.getContextExpressionAccess().getSub_expAssignment_1_1(), "rule__ContextExpression__Sub_expAssignment_1_1");
					put(grammarAccess.getFilterExpressionAccess().getCell_typeAssignment_2(), "rule__FilterExpression__Cell_typeAssignment_2");
					put(grammarAccess.getStateFilterExpressionAccess().getCell_stateAssignment_2(), "rule__StateFilterExpression__Cell_stateAssignment_2");
					put(grammarAccess.getCountExpressionAccess().getOpAssignment_4_0(), "rule__CountExpression__OpAssignment_4_0");
					put(grammarAccess.getCountExpressionAccess().getCmpValAssignment_4_1(), "rule__CountExpression__CmpValAssignment_4_1");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			uk.ac.kcl.inf.zschaler.gridgames.ui.contentassist.antlr.internal.InternalGridGameParser typedParser = (uk.ac.kcl.inf.zschaler.gridgames.ui.contentassist.antlr.internal.InternalGridGameParser) parser;
			typedParser.entryRuleGridGame();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}
	
	public GridGameGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(GridGameGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
