/*
 * generated by Xtext
 */
package uk.ac.kcl.inf.zschaler.gridgames.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import uk.ac.kcl.inf.zschaler.gridgames.ui.internal.GridGameActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class GridGameExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return GridGameActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return GridGameActivator.getInstance().getInjector(GridGameActivator.UK_AC_KCL_INF_ZSCHALER_GRIDGAMES_GRIDGAME);
	}
	
}
