/*
 * generated by Xtext
 */
package uk.ac.kcl.inf.zschaler.gridgames.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import uk.ac.kcl.inf.zschaler.gridgames.services.GridGameGrammarAccess;

public class GridGameParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private GridGameGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected uk.ac.kcl.inf.zschaler.gridgames.parser.antlr.internal.InternalGridGameParser createParser(XtextTokenStream stream) {
		return new uk.ac.kcl.inf.zschaler.gridgames.parser.antlr.internal.InternalGridGameParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "GridGame";
	}
	
	public GridGameGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(GridGameGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
