/*
 * generated by Xtext
 */
package uk.ac.kcl.inf.zschaler.gridgames.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class GridGameAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("uk/ac/kcl/inf/zschaler/gridgames/parser/antlr/internal/InternalGridGame.tokens");
	}
}
