/*
 * generated by Xtext
 */
package uk.ac.kcl.inf.zschaler.gridgames.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;

public class AbstractGridGameValidator extends org.eclipse.xtext.validation.AbstractDeclarativeValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(uk.ac.kcl.inf.zschaler.gridgames.gridGame.GridGamePackage.eINSTANCE);
		return result;
	}
}
