/*
 * generated by Xtext
 */
package uk.ac.kcl.inf.zschaler.gridgames.validation

import org.eclipse.xtext.validation.Check
import uk.ac.kcl.inf.zschaler.gridgames.gridGame.GridGame
import uk.ac.kcl.inf.zschaler.gridgames.gridGame.GenerationalContexts

/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
class GridGameValidator extends AbstractGridGameValidator {

//  public static val INVALID_NAME = 'invalidName'
//
//	@Check
//	def checkGreetingStartsWithCapital(Greeting greeting) {
//		if (!Character.isUpperCase(greeting.name.charAt(0))) {
//			warning('Name should start with a capital', 
//					MyDslPackage.Literals.GREETING__NAME,
//					INVALID_NAME)
//		}
//	}

	@Check
	def checkRecursiveContextTriggers (GridGame gg) {
		if (!gg.options.exists[o | o instanceof GenerationalContexts]) {
			warning ("You may need to check for potential recursive context triggers.", null, "Recursive context triggers")
		}
	}
}
