/*
 * generated by Xtext
 */
package uk.ac.kcl.inf.zschaler.gridgames;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class GridGameUiInjectorProvider implements IInjectorProvider {
	
	@Override
	public Injector getInjector() {
		return uk.ac.kcl.inf.zschaler.gridgames.ui.internal.GridGameActivator.getInstance().getInjector("uk.ac.kcl.inf.zschaler.gridgames.GridGame");
	}
	
}
